### ISSUE TITLE
sdk-vue 0.0.5: Layout and form components not available

### ISSUE THREAD

**Issue by canleon** [BuilderIO/builder#1356]
**Describe the bug**
BuilderIO does not feature layout or form components in the web interface. This bug might also be present in prior versions of this SDK.

**To Reproduce**
1. Setup sdk-vue in e.g. version 0.0.5
2. Look at the insert tab in BuilderIO

**Expected behavior**
The layout and form component groups should be visible containing the corresponding components.

**Screenshots**
No layout and form component groups visible in builder.io/sdk-vue 0.0.5:
<img width="347" alt="grafik" src="https://user-images.githubusercontent.com/62016454/200834321-0f2ec914-0ef0-4c0c-81d9-24c0def479e7.png">

Layout and form component groups visible in builder.io/vue 0.1.12:
<img width="347" alt="grafik" src="https://user-images.githubusercontent.com/62016454/200834935-9e3d9c7f-f9a0-4c08-a0e1-843f8107fe94.png">

**Additional context**
This problem might apply for other components as well.

**Comment by samijaber** [comment]
@canleon These are still under active development for the new SDKs. Will update this issue when they are released

**Comment by canleon** [comment]
Thanks @samijaber for the reply. I actually thought about that, but I assumed since the components are already implemented, that mitosis should take care of this and that it's just a miscofiguration. Anyway, thanks for keeping us up to date if there are any news.

**Comment by jbool24** [comment]
@samijaber @steve8708 PLEASE HELP 🙏

Apologies to post this here however but it is relevant. I tried to engage with support and that was a HUGE fail. Is there any update on the stability of this SDK? This seems to be broken but I can't even tell because only Page models are the only thing that seems to work as expected when following any guides on https://www.builder.io/c/docs or https://www.builder.io/c/blueprints

There are a ton of dependencies between the examples that are spread all over the documentations and I can't figure out what is current. Here is some examples that show how different...

**Examples in the editor for Vue/Nuxt**
![image](https://github.com/BuilderIO/builder/assets/13041345/124def76-9d2b-4d85-8322-d626f92ede7e)
![image](https://github.com/BuilderIO/builder/assets/13041345/a1a5e0d6-b5f3-4c08-829a-b8dbfa4d85cd)
**Examples for Section Type models following Announcement bar guide with Vue/Nuxt** 
no mention of API Key or if this goes in nuxt.config.js or if it needs to be on the Content component and is this the same as RenderContent as mention above??? 
![image](https://github.com/BuilderIO/builder/assets/13041345/bec7276e-b4fa-4614-93d6-8205d6d1217d)
The expected defaults in the nuxt world that has a module is that configs like API-KEY goes in the nuxt.config.js but I don't see anywhere if thats what we need to do.
![image](https://github.com/BuilderIO/builder/assets/13041345/345c3d2b-3a7f-4796-b48f-63d8212bd059)
**Editorial Example**
This one shows both fetchOneEntry
![image](https://github.com/BuilderIO/builder/assets/13041345/128361fe-28ac-44d1-afe3-b18734f55ce2)



Main Questions:
1. Do we use `builder.init()` or is that the old vue SDK and we should use `@builder.io/sdk-vue` instead and set an api-key prop on the component?
2. If using component props is the correct method to init, why do we need a fetch function to call the data (that also has api-key as params? Is that not what the Content is doing with the api-key prop?
3. Is there really a helper method getContent? Or is it fetchOneEntry? Or do we just use Fetch API and a rest endpoint?

I'm not bitching here. I love what this project is aiming to do have a lot of Vue/Nuxt project that could use Builder.io 😍 But if these example aren't concrete its a huge blocker to getting started. I know there is a lot of busy work going on so I mentioned to Support and Partner Program reps that I would be willing to help clean up the docs and contribute back if I can get someone to explain the appropriate current usage. Either way can we close the gaps for vue3 and nuxt3 framework guides so they agree site-wide across the documentation and examples? I really want to get using this a lot but feeling frustrated at every step onboarding.

**Comment by samijaber** [comment]
@jbool24 Please file a separate issue, as your questions are not related to the original issue here.

As for the original issue: We actually added Layout and Form components back in 0.13.2. https://github.com/BuilderIO/builder/blob/main/packages/sdks/output/vue/CHANGELOG.md#0132

I am closing this issue since it's been resolved a while back.
