### ISSUE TITLE
amp-img sizes attribute sizes images in half on mobile viewports.

### ISSUE THREAD

**Issue by homanp** [BuilderIO/builder#154]
The `sizes` attribute on `amp-img`-tags sizes images to half the viewport event though the parent element has a 100% width. The amp-img nodes also has a redundant CSS class with `position: absolute`

Any suggestions on how to resolve this issue?

<img width="1792" alt="Screenshot 2020-04-29 at 08 44 25" src="https://user-images.githubusercontent.com/2464556/80567915-47560000-89f6-11ea-8519-9c6f62fd9c79.png">

<img width="1792" alt="Screenshot 2020-04-29 at 08 49 52" src="https://user-images.githubusercontent.com/2464556/80567996-77050800-89f6-11ea-817f-3fd9daf71203.png">

**Comment by kevva** [comment]
This is related to https://github.com/BuilderIO/builder/commit/734de9b524412beee8123f14dd25146b017c93b7. Without the sizer that sets padding, the image needs an explicit height since it's absolutely positioned.

AMP maintains aspect ratio for the images already, as long as you set `width` and `height`, so you should probably remove these lines as well https://github.com/BuilderIO/builder/blob/master/packages/react/src/blocks/Image.tsx#L191-L197.

**Comment by mrkoreye** [comment]
Thanks for the tip, @kevva! I will take a look today

**Comment by kevva** [comment]
It works as far as I can see now. @homanp, can you confirm?

**Comment by homanp** [comment]
Works like a charm @mrkoreye. Closing :)
