### ISSUE TITLE
SvelteKit dynamic url binding not working with mixed model content for CSR mode

### ISSUE THREAD

**Issue by abhisheksaini1** [BuilderIO/builder#1815]
Hi,

Im using SvelteKit to create a sample app, and facing issue with RenderContent component. I have passed data prop to it with cms data model and load logic has been defined in page.js for both SSR and CSR. Single page model is being used to handle the dynamic URLs. I have bound text fields to state data through the pagebuilder ui.

The SSR is working absolutely fine with both dynamic URLs I have created show different content. However the CSR isn't, when I click the nav link, title etc.. update but not the RenderContent component. It shows the SSR content only.

Not sure if it's an issue but why is this component not rerendering when everything else is?

**Comment by samijaber** [comment]
@abhisheksaini1 This is due to a recent update to how our Svelte SDK works.

We recently updated the examples to reflect how to handle this:

https://github.com/BuilderIO/builder/blob/d37af54184529f1f87250cb48b8b802d2abe30d3/packages/sdks/e2e/sveltekit/src/routes/%5B...catchall%5D/%2Bpage.svelte#L29-L31

You need to use a `#key` block to wrap the `RenderContent` component. This will fix client-side navigation.

In the future, we will hopefully make it so that you don't need to do this.
