### ISSUE TITLE
We are seeing double-loading of the builder page in our app

### ISSUE THREAD

**Issue by JefferyReidKnowde** [BuilderIO/builder#27]
We have placed the builder code into our pages to allow editing through builder. However, when our page loads, builder seems to be sending two calls to your CDN which forces our page to double load and to load slowly.

**Comment by ca136** [comment]
@JefferyReidKnowde this looks like it might be the same as https://github.com/BuilderIO/builder/issues/19. If so, I'll close this out and we can track the work in the other ticket.

**Comment by steve8708** [comment]
Yeah I think this is a combination of requires explanation and possible duplicate. So - what Builder does when you load it is it requests/sends 2 things

1) Static prerendered HTML
2) JS + JSON to "hydrate" the HTML

Why?

In 99% of cases this is the best option. When in production, and assuming you have caching set to the default or a reasonable number for your traffic load, the prerendered HTML will always be the fastest way to get your Builder content loaded. 

But to power anything dynanamic - be it custom code you have added, custom interactions you have added, animation, dynamnic components (e.g. carousel) - you need the JS + JSON to load. So Builder lazily loads this after the HTML - such that the user can see the page almost immediately (adduming it's cached - on staging if you have cache set to something small like 1 you will have to wait for a fresh render every time), and then all interactivity will be adde din shortly thereafter.

This is a very common approach used by Angular Universal, React/Next.js, Gatsby, etc as the optimal way to have fast performing and dynamic pages. 

But you have options here

You can set `prerender="false"` to only make the JS+JSON request. This will be a tad bit slower in production
Or, you can set `hydrate="false"`to only load the HTML, but you can have _nothing_ interactive or dynamic on your pages

All of that said, we have another ticket for a bug in the latest Angular SDK where you experience a flash when the hydration happens that shouldn't happen, and will be fixed with that ticket

Anyway, hope this information helps. Closing this particular ticket as no dev work seems to be needed as we already have the other one #19

**Comment by lyczos** [comment]
@ca136 @steve8708 actually setting prerender to false is not working (request is made but nothing is displayed)

**Comment by steve8708** [comment]
Thanks for letting us know @lyczos, #36 created to address
