### ISSUE TITLE
`SIGSEGV` panic on Node.js 20 with `@builder.io/react`

### ISSUE THREAD

**Issue by ChibiBlasphem** [BuilderIO/builder#2966]
**Describe the bug**

After upgrading node.js to 20 from 18 our Next.js dev (`next dev`) is broken and panics with a `SIGSEGV` (`Command failed with signal "SIGSEGV"`) when `BuilderComponent` is in the render tree of the page.

**Additionnal information**
CI build (`next build`) is ok with node.js 20 (image `node:20-alpine3.18`)

**Using**
@builder.io/react 3.2.0
Next.js 12.3.0
Node >= 20

**Expected behavior**
Expect the app to run normally as it does with node 18

**Comment by samijaber** [comment]
TL;DR: `NODE_OPTIONS=--no-node-snapshot next build` should fix your issue.

This is due to an issue with the `isolated-vm` dependency when used in Node v20 on an M1 Mac.

Our gen2 SDKs have a fix for it: https://github.com/BuilderIO/builder/tree/main/packages/sdks/#node-v20--m1-macs-apple-silicon-support

We will backport this fix to the gen1 React SDK soon

**Comment by samijaber** [comment]
Should be fixed in latest: https://github.com/BuilderIO/builder/blob/main/packages/react/CHANGELOG.md#321
