### ISSUE TITLE
BUG: Builder Contentful Plugin Dynamic Data Binding Issue

### ISSUE THREAD

**Issue by ashraf-gemini** [BuilderIO/builder#3058]
**Describe the bug**
After connecting my Contentful CMS with Builder.io and setting up dynamic data binding for UI elements to Contentful entries, updates to the Contentful entries are not reflected in the Builder.io UI. It appears that the data is being cached indefinitely based on an identifier, preventing the display of updated content.

**To Reproduce**
1. Connect Contentful CMS to Builder.io using the Builder Contentful plugin.
2. Bind a UI element in Builder.io to display data from a Contentful entry.
3. Update the content of the bound entry in Contentful CMS.
4. Check the UI element in Builder.io for the updated content.

**Expected behavior**
When a Contentful entry that a Builder.io UI element is bound to is updated, the change should be immediately reflected in the Builder.io interface. Dynamic data binding should ensure that content updates in Contentful are accurately displayed in Builder.io without manual intervention or delays.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Additional context**
This issue is critically blocking a use case for our team, as timely updates and accuracy of content displayed through Builder.io are crucial for our operations. Any assistance in resolving this caching issue to ensure that updates in Contentful are properly propagated to Builder.io would be greatly appreciated.

---

**Comment by amangautam7** [comment]
A quick resolution is appreciated, Thanks!

**Comment by mrkoreye** [comment]
Hi @ashraf-gemini , can you please share a builder.io content entry link to an entry where you are seeing this behavior? The link will look like builder.io/content/<entry-id>, it is the page where you see the editor and can edit content entries. This will help us diagnose the issue.

**Comment by ashraf-gemini** [comment]
Hi Korey

Here's the page entry link ->
https://builder.io/content/074211b4949e41ffb3ac838581837818

Regards,
Mohd Ashraf

**Comment by mrkoreye** [comment]
@ashraf-gemini is the issue that the content coming from Contentful is never updated within Builder, or is it that the update takes a while to show? Because both Contentful and Builder have layers of caching, a delay in content showing up is to be expected. What about on the live site when publishing content from Builder, does the data from Contentful eventually show up correctly? Again, a delay in the content update showing is to be expected in order to ensure the best performance for all site visitors.

If you are having issues with pulling Contentful data, you can instead create and manage that data within Builder instead using a data model: https://www.builder.io/c/docs/models-data

**Comment by ashraf-gemini** [comment]
@mrkoreye I suggest having a CTA to bust the cache on-demand and fetch the updated data. Think about the delay incurred on the go-live of a feature update or users being served stale data which could be faulty/ placeholder/ irrelevant etc.

**Comment by mrkoreye** [comment]
@ashraf-gemini that is a good idea, please head to ideas.builder.io and share it as a new idea to improve the product. Since this issue is a feature request for the Builder.io web application, I am going to close it for now.
