### ISSUE TITLE
Angular SDK Gen 2 release estimate? Current branch of dev?

### ISSUE THREAD

**Issue by fabm22** [BuilderIO/builder#3319]
Reading here https://www.builder.io/c/docs/sdk-comparison that Angular SDK Gen 2 is "currently under development" I would like to know  if there is an estimate when it might be ready AND if there is dev code branch where we can track the current advancement and possibly contribute?
Thanks a lot.

**Comment by samijaber** [comment]
> I would like to know if there is an estimate when it might be ready 

No estimate, but it is a top priority and actively being worked on by our team.

> AND if there is dev code branch where we can track the current advancement 

The Gen2 Angular SDK is located here: https://github.com/BuilderIO/builder/tree/main/packages/sdks/output/angular

As you can see, it is still undocumented and not meant to be used by customers. You can track its releases with this filter: https://github.com/BuilderIO/builder/releases?q=sdk-angular&expanded=true

Once the SDK is in a more stable state, we will make a `v0.1.0` release so it's in beta, followed by a `v1.x` release once it reaches parity with other Gen2 SDKs.

> and possibly contribute?

Unfortunately not at this time, due to the complex nature of our SDK codebase

**Comment by fabm22** [comment]
Thanks for comprehensive answer and explanations and pointers! Can't wait to check it out and at some point check Mitosis. Quite the undertaking you guys dared to solve looking from outside ! Thanks for the work.
