### ISSUE TITLE
Does not load up on Brave Browser unless you disable Brave's Shield 

### ISSUE THREAD

**Issue by Zeyu-Li** [BuilderIO/builder#662]
If you do not disable the Brave Shield, it will attempt to load the page continuously (and show the "We are having trouble connecting to your site" popup) even after allowing Insecure content

**Comment by mrkoreye** [comment]
Hi @Zeyu-Li, sorry you are running into an issue!

Are you referring to a page published with builder content on it not loading? If so, can you share the URL it is happening on?

Or are you talking about not being able to load the preview inside of the builder editor? If it is the builder editor not loading properly, can you share the content entry url (builder.io/content/<entry-id>) that you are unable to load?

**Comment by gg-craig** [comment]
@mrkoreye can confirm - just spent hours on this and the issue was brave, not builder.io.

As you can see by the image below, allowing ads and tracking allowed me to load builder, but I also added the ability to load insecure content from my localhost in brave. 

![image](https://user-images.githubusercontent.com/94721338/191572242-296e957e-2f35-4a78-a053-f8068f6ff320.png)

**Comment by sidmohanty11** [comment]
@Zeyu-Li Thanks for this!

**Comment by Zeyu-Li** [comment]
no problem
